# Generated by Django 5.0.4 on 2024-05-05 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todotask_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.customuser'),
        ),
    ]
